defaults:
  - hparams: default
  - embedding: sciplex_lincs_genes
  - additional_params: default

enable_cpa_mode: False
load_pretrained: True
append_ae_layer: False
pretrained_model_path: ${training.save_dir}
pretrained_model_hashes: 
  model: omon82fh   
