name: chemical_CPA
channels:
  - conda-forge
dependencies:
  - python=3.7
  - adjusttext
  - matplotlib
  - numpy
  - pandas
  - scanpy
  - scipy
  - seaborn
  - scikit-learn
  - submitit
  - jupyter
  - jupytext
  - pytorch::pytorch
  - torchmetrics
  - h5py<3.2
  - cudatoolkit=11.3
  - dglteam::dgl-cuda11.3
  - deepchem
  - rdkit=2021.09.2
  - pytest
  - pyarrow
  - pre-commit
  - seml
  - py-spy
  - pip
  - pip:
      - sfaira
      - tensorflow-gpu
      - 'git+git://github.com/siboehm/dgl-lifesci@jtvae#subdirectory=python'
