defaults: 
  - _self_
  - model: finetune_combinatorial 
  - dataset: combinatorial 
  - training: default 
  - wandb: default
  - hydra: default

profiling.run_profiler: False
profiling.outdir: "./" 
